name: RocketBoots
main: com.disabledhamster.bukkit.rocketboots.RocketBoots
description: Various rocket boots, fun and useful, for flying around your server
author: DisabledHamster
version: 0.4

commands:
    rocketboots:
        description: Disable or enable RocketBoots (for yourself)
        usage: /<command> [on|off]
        aliases: rb
permissions:
    rocketboots.*:
        description: Give all permissions
        children:
            rocketboots.boots.gold: true
            rocketboots.boots.leather: true
            rocketboots.boots.chainmail: true
            rocketboots.boots.diamond: true
            rocketboots.boots.iron: true
            rocketboots.feather: true
            rocketboots.launchPlayers: true
    rocketboots.boots.gold:
        description: Can use gold boots
    rocketboots.boots.leather:
        description: Can use leather boots
    rocketboots.boots.chainmail:
        description: Can use chainmail boots
    rocketboots.boots.diamond:
        description: Can use diamond boots
    rocketboots.boots.iron:
        description: Can use iron boots
    rocketboots.feather:
        description: Can use the feather to stop in mid-air while flying
    rocketboots.launchPlayers:
        description: Can launch players when using iron / leather boots (without this, only animals / mobs will be launched)
