name: RocketBoots
main: com.disabledhamster.bukkit.rocketboots.RocketBoots
description: Various rocket boots, fun and useful, for flying around your server
author: DisabledHamster
version: 0.3.7

commands:
    rocketboots:
        description: Disable or enable RocketBoots (for yourself)
        usage: /<command> [on|off]
    rb:
        # alias of /rocketboots
        description: Disable or enable RocketBoots (for yourself)
        usage: /<command> [on|off]

permissions:
    rocketboots.*:
        description: Give all permissions
        children:
            rocketboots.boots.gold: true
            rocketboots.boots.leather: true
            rocketboots.boots.chainmail: true
            rocketboots.boots.diamond: true
            rocketboots.boots.iron: true
            rocketboots.feather: true
            rocketboots.launchPlayers: true
    rocketboots.boots.gold:
        description: Can use gold boots
        default: op
    rocketboots.boots.leather:
        description: Can use leather boots
        default: op
    rocketboots.boots.chainmail:
        description: Can use chainmail boots
        default: op
    rocketboots.boots.diamond:
        description: Can use diamond boots
        default: op
    rocketboots.boots.iron:
        description: Can use iron boots
        default: op
    rocketboots.feather:
        description: Can use the feather to stop in mid-air while flying
        default: op
    rocketboots.launchPlayers:
        description: Can launch players when using iron / leather boots (without this, only animals / mobs will be launched)
        default: op